serviceAccountName: prod-workload

app:
  image:
    tag: manual-48fe847
  hpa:
    minReplicas: 2
    maxReplicas: 7

postgres:
  storageClassName: gp3-prod
  internalHostname: postgres-prod.gitops-project.internal
